# Generated by Django 5.2.8 on 2025-12-03 02:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('fullName', models.CharField(max_length=255)),
                ('functionSummary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneticVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chromosome', models.CharField(max_length=5)),
                ('position', models.IntegerField()),
                ('referenceBase', models.CharField(max_length=1)),
                ('alternateBase', models.CharField(max_length=1)),
                ('impact', models.CharField(choices=[('Missense', 'Missense'), ('Frameshift', 'Frameshift'), ('Nonsense', 'Nonsense'), ('Silent', 'Silent')], max_length=20)),
                ('geneId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='genomic_api.gene')),
            ],
        ),
        migrations.CreateModel(
            name='PatientVariantReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patientId', models.UUIDField()),
                ('detectionDate', models.DateField()),
                ('alleleFrequency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('variantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientReports', to='genomic_api.geneticvariant')),
            ],
        ),
    ]
